# render.yaml (at repo root)

services:
  - name: ai-workout-analyzer
    type: web
    env: python
    plan: free
    region: osaka
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web.app:app --host 0.0.0.0 --port $PORT

  - name: ai-workout-coach-agent
    type: worker
    env: python
    plan: free
    region: osaka
    buildCommand: pip install -r requirements.txt
    startCommand: python coach_agent.py
