# render.yaml

services:
  - type: web               # This is a web service (HTTP) so Render will route traffic here
    name: ai-workout-analyzer
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true        # Rebuild + redeploy on every git push
